// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UserApiDAL.Migrations
{
    [DbContext(typeof(CandidatesContext))]
    [Migration("20230425191729_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Candidates", b =>
                {
                    b.Property<int>("candidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("beginYear")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("lastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("candidateId");

                    b.ToTable("candidates");
                });

            modelBuilder.Entity("CandidatesLanguage", b =>
                {
                    b.Property<int>("candidatescandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("languagesCodeslanguageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("candidatescandidateId", "languagesCodeslanguageId");

                    b.HasIndex("languagesCodeslanguageId");

                    b.ToTable("CandidatesLanguage");
                });

            modelBuilder.Entity("Language", b =>
                {
                    b.Property<int>("languageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("languageId");

                    b.ToTable("language");
                });

            modelBuilder.Entity("CandidatesLanguage", b =>
                {
                    b.HasOne("Candidates", null)
                        .WithMany()
                        .HasForeignKey("candidatescandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Language", null)
                        .WithMany()
                        .HasForeignKey("languagesCodeslanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
